# LagXpert - General Configuration

# 🧩 Modules activation
modules:
  mobs: true
  storage: true
  redstone: true
  alerts: true
  task: true

# 🛡 Permissions & control
permissions:
  bypass-enabled: true

# 🧠 Debug mode (shows extra console logs for diagnostics)
debug: false

